{"errorMessage": "An error occurred (AuthorizationError) when calling the Publish operation: User: arn:aws:sts::266735808339:assumed-role/lambda-piped-2-MyLambdaFunctionRole-9l5zRkvZg1r7/lambda-piped-fn is not authorized to perform: SNS:Publish on resource: arn:aws:sns:eu-west-1:266735808339:ec2-uptime-alert because no identity-based policy allows the SNS:Publish action", "errorType": "AuthorizationErrorException", "requestId": "9f7fea59-33fb-4608-a8a4-b8f25480b2d3", "stackTrace": ["  File \"/var/task/main.py\", line 23, in lambda_handler\n    sns_client.publish(\n", "  File \"/var/lang/lib/python3.12/site-packages/botocore/client.py\", line 569, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n", "  File \"/var/lang/lib/python3.12/site-packages/botocore/client.py\", line 1023, in _make_api_call\n    raise error_class(parsed_response, operation_name)\n"]}